# Generated by Django 5.0.2 on 2024-04-04 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_priority_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_column', models.IntegerField(default='2')),
                ('end_column', models.IntegerField(default='6')),
                ('pic_column', models.IntegerField(default='8')),
                ('email_column', models.IntegerField(default='61')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.user')),
            ],
        ),
    ]
