# Generated by Django 5.0.2 on 2024-04-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
