# Generated by Django 5.0.2 on 2024-04-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_settings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='start_row',
            field=models.IntegerField(default='5'),
        ),
    ]
