# Generated by Django 5.0.2 on 2024-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_settings_start_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='gannt_start_row',
            field=models.IntegerField(default='9'),
        ),
    ]
