# Generated by Django 5.0.2 on 2024-04-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_settings_gannt_start_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='gannt_start_row',
            new_name='gannt_start_column',
        ),
    ]
