# Generated by Django 5.0.2 on 2024-04-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_gannt_start_row_settings_gannt_start_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='week_number_row',
            field=models.IntegerField(default='4'),
        ),
    ]
