# Generated by Django 5.0.2 on 2024-04-04 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_settings_week_number_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.user'),
        ),
    ]
