# Generated by Django 5.0.2 on 2024-04-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_settings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='apps.user'),
            preserve_default=False,
        ),
    ]
