# Generated by Django 5.0.2 on 2024-04-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_settings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.IntegerField(),
        ),
    ]
